
# Bot settings
# Please set bot token, admins, and authorized users in config.secret.yaml.

# If true, the bot will be switched to a test bot. You have to set test token in config.secret.yaml as well if true.
test mode: false
# If true, only authorized users can use /subscribe function.
require auth: true


# Job settings

# The maximum number of subscriptions a user can have
job limit: 3
# Bot query timeout time in seconds. If the MVC website does not response in {timeout} sec, return error.
timeout: 3
# Bot query interval in seconds. It means check appointments every {query interval} sec.
query interval: 120